# Generated by Django 5.0.6 on 2024-06-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(default='hms_adminl123', max_length=50)),
                ('admin_password', models.CharField(default='admin123', max_length=20)),
            ],
        ),
    ]
