# Generated by Django 5.0.6 on 2024-06-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin_details',
            new_name='admin_detail',
        ),
    ]
