# Generated by Django 5.0.6 on 2024-06-24 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_phone_doctor_specility_doctor_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Joining_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
        ),
    ]
