# Generated by Django 5.0.6 on 2024-06-13 03:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(default='', max_length=50)),
                ('Last_name', models.CharField(default='', max_length=50)),
                ('Email', models.CharField(max_length=30)),
                ('Phone', models.CharField(default='', max_length=40)),
                ('Password', models.CharField(default='', max_length=20)),
                ('DOB', models.CharField(default='', max_length=10)),
                ('Address', models.CharField(default='', max_length=30)),
                ('Date_time', models.CharField(default=django.utils.timezone.now, max_length=10)),
            ],
        ),
    ]
