# Generated by Django 5.0.6 on 2024-06-21 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blood_group', models.CharField(default='', max_length=20)),
                ('Gender', models.CharField(default='', max_length=20)),
                ('department', models.CharField(default='', max_length=20)),
                ('patient_fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient_register')),
            ],
        ),
    ]
