# Generated by Django 5.0.6 on 2024-06-25 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Appointment_date',
            field=models.CharField(default=datetime.datetime(2024, 6, 25, 13, 11, 44, 766558, tzinfo=datetime.timezone.utc), max_length=20),
        ),
    ]
