# Generated by Django 5.0.6 on 2024-06-26 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_appointment_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='department',
            new_name='Disease',
        ),
        migrations.AddField(
            model_name='patient_register',
            name='Image',
            field=models.ImageField(default='https://img.freepik.com/free-vector/user-circles-set_78370-4704.jpg?size=626&ext=jpg&ga=GA1.1.199161677.1717694373&semt=ais_user', upload_to=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Appointment_date',
            field=models.CharField(default=datetime.datetime(2024, 6, 26, 3, 6, 27, 482435, tzinfo=datetime.timezone.utc), max_length=50),
        ),
    ]
