# Generated by Django 5.0.6 on 2024-06-28 12:30

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_alter_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Appointment_date',
            field=models.CharField(default=datetime.datetime(2024, 6, 28, 12, 30, 16, 145095, tzinfo=datetime.timezone.utc), max_length=50),
        ),
        migrations.AlterField(
            model_name='patient_register',
            name='Date_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment_fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.appointment')),
                ('patient_fkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient_register')),
            ],
        ),
    ]
